#!/usr/bin/env python3
"""Generate tests/unit/simlib_word_cases.h: word-cell answers computed by Yosys simlib in Icarus.

Usage: tools/sim-check/gen_simlib_cases.py [--simlib PATH] [--out PATH]

Each case instantiates one simlib cell ($add ... $ge, $not) with fixed parameters and constant
inputs; iverilog/vvp print Y. The header gives test_sim_word.c expected values that do not come
from the simulator's own model. Deterministic (fixed seed). Needs iverilog, vvp and clang-format.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
import tempfile
from dataclasses import dataclass

BINARY = ["$add", "$sub", "$mul", "$and", "$or", "$xor", "$eq", "$ne", "$lt", "$le", "$gt", "$ge"]
UNARY = ["$not"]
WIDTHS = [1, 7, 64, 65]
SIGNS = [(0, 0), (0, 1), (1, 0), (1, 1)]
PER_COMBO = 5
SEED = 2026


@dataclass
class Case:
    cell: str
    a_signed: int
    b_signed: int
    aw: int
    bw: int
    yw: int
    a_val: int
    b_val: int


def value(rng: random.Random, width: int) -> int:
    """Random bits, the MSB set half of the time (exercises sign extension)."""
    val = rng.getrandbits(width)
    if rng.random() < 0.5:
        val |= 1 << (width - 1)
    return val


def make_cases() -> list[Case]:
    rng = random.Random(SEED)
    cases: list[Case] = []
    for cell in BINARY + UNARY:
        for a_signed, b_signed in SIGNS:
            if cell in UNARY and b_signed:
                continue
            for _ in range(PER_COMBO):
                aw, bw, yw = (rng.choice(WIDTHS) for _ in range(3))
                if cell in UNARY:
                    bw = 1
                cases.append(
                    Case(cell, a_signed, b_signed, aw, bw, yw, value(rng, aw), value(rng, bw))
                )
    return cases


def testbench(cases: list[Case]) -> str:
    lines = ["module tb;"]
    for i, case in enumerate(cases):
        lines.append(f"  wire [{case.yw - 1}:0] y{i};")
        if case.cell in UNARY:
            params = f".A_SIGNED({case.a_signed}), .A_WIDTH({case.aw}), .Y_WIDTH({case.yw})"
            ports = f".A({case.aw}'h{case.a_val:x}), .Y(y{i})"
        else:
            params = (
                f".A_SIGNED({case.a_signed}), .B_SIGNED({case.b_signed}), "
                f".A_WIDTH({case.aw}), .B_WIDTH({case.bw}), .Y_WIDTH({case.yw})"
            )
            ports = f".A({case.aw}'h{case.a_val:x}), .B({case.bw}'h{case.b_val:x}), .Y(y{i})"
        lines.append(f"  \\{case.cell} #({params}) u{i} ({ports});")
    lines.append("  initial begin")
    lines.append("    #1;")
    lines.extend(f'    $display("%h", y{i});' for i in range(len(cases)))
    lines.append("  end")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


def simulate(cases: list[Case], simlib: str) -> list[str]:
    with tempfile.TemporaryDirectory() as tmp:
        tb_path = os.path.join(tmp, "tb.v")
        vvp_path = os.path.join(tmp, "tb.vvp")
        with open(tb_path, "w", encoding="utf-8") as handle:
            handle.write(testbench(cases))
        subprocess.run(["iverilog", "-g2012", "-o", vvp_path, tb_path, simlib], check=True)
        out = subprocess.run(["vvp", "-n", vvp_path], check=True, capture_output=True, text=True)
    answers = [line.strip() for line in out.stdout.splitlines() if line.strip()]
    if len(answers) != len(cases) or any("x" in a or "z" in a for a in answers):
        sys.exit("gen_simlib_cases: unexpected simulator output")
    return answers


def header(cases: list[Case], answers: list[str]) -> str:
    rows = [
        f'    {{"{c.cell}", {c.a_signed}, {c.b_signed}, {c.aw}, {c.bw}, {c.yw}, '
        f'"{c.a_val:x}", "{c.b_val:x}", "{y}"}},'
        for c, y in zip(cases, answers, strict=True)
    ]
    return (
        "/* simlib_word_cases.h — word-cell answers from Yosys simlib.v run in Icarus Verilog.\n"
        " * Generated by tools/sim-check/gen_simlib_cases.py; do not edit. */\n"
        "static const simlib_case k_simlib_cases[] = {\n" + "\n".join(rows) + "\n};\n"
    )


def main() -> int:
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    default_simlib = os.path.expanduser("~/odin3-ws/external/yosys/techlibs/common/simlib.v")
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--simlib", default=default_simlib)
    parser.add_argument("--out", default=os.path.join(root, "tests/unit/simlib_word_cases.h"))
    args = parser.parse_args()
    cases = make_cases()
    answers = simulate(cases, args.simlib)
    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(header(cases, answers))
    subprocess.run(["clang-format", "-i", args.out], check=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
