"""golden-sample: choose the representative subset of goldens that odin3-golden commits.

Usage::

    golden-sample [--golden DIR] [--per-group N] [--max-blif-mb MB] [--write]

The full golden set (every BLIF written by ``tools/run-oracle.sh``) is too large for GitHub, so
the odin3-golden repo tracks every ``.prov``/``.log`` but only a sample of the BLIFs; the full
set is archived elsewhere (see the odin3-golden README).  The sample is deterministic:

* Designs are grouped by ``regression/verilog/<category>``, ``vtr``, or otherwise their first
  name component.
* A design is eligible when, on every arch present, both tools have ``status=ok`` and each of its
  BLIFs is at most ``--max-blif-mb``.
* From each group the eligible designs are sorted by total BLIF size (largest arch), and
  ``--per-group`` of them are taken at evenly spaced ranks (smallest, ..., largest), so a group
  contributes small, medium and large designs.  ``quickstart/blink`` (the Phase 0 sanity design)
  is always included when present.

Without ``--write`` the selection is only summarized.  With ``--write`` the managed block of
``<golden>/.gitignore`` is regenerated: ``*.blif`` is ignored and each sampled BLIF is
re-included with a ``!/path`` line.

Exit 0 on success, 2 on usage or input error.
"""

from __future__ import annotations

import argparse
import sys
from collections import defaultdict
from collections.abc import Sequence
from dataclasses import dataclass, field
from pathlib import Path

TOOLS = ("parmys", "odin")
# Included whenever every run is ok, regardless of size: the Phase 0 sanity design (a few KB).
ALWAYS = ("quickstart/blink",)
BEGIN = "# BEGIN golden-sample (generated by odin3/tools/golden-sample --write; do not edit)"
END = "# END golden-sample"


class SampleError(Exception):
    """Input error (exit 2)."""


@dataclass
class Design:
    """One design name across all arches: its BLIFs and whether every run succeeded."""

    name: str
    blifs: list[Path] = field(default_factory=list)
    arch_bytes: dict[str, int] = field(default_factory=dict)
    all_ok: bool = True
    max_blif: int = 0

    @property
    def size(self) -> int:
        return max(self.arch_bytes.values(), default=0)


def group_of(name: str) -> str:
    parts = name.split("/")
    if parts[:2] == ["regression", "verilog"] and len(parts) > 3:
        return "/".join(parts[:3])
    return parts[0]


def read_status(prov: Path) -> str:
    for line in prov.read_text().splitlines():
        if line.startswith("status="):
            return line.removeprefix("status=")
    raise SampleError(f"{prov}: no status= line")


def scan(golden: Path) -> dict[str, Design]:
    """Collect every design under <golden>/<arch>/<name>/ keyed by name."""
    archs = sorted(p.name for p in golden.iterdir()
                   if p.is_dir() and not p.name.startswith(".") and next(p.rglob("*.prov"), None))
    if not archs:
        raise SampleError(f"{golden}: no <arch>/ directories with .prov files")
    designs: dict[str, Design] = {}
    for arch in archs:
        for prov in sorted((golden / arch).rglob("*.prov")):
            leaf, _, tool = prov.name.removesuffix(".prov").rpartition(".")
            if not leaf or tool not in TOOLS:
                raise SampleError(f"{prov}: not <leaf>.<{'|'.join(TOOLS)}>.prov")
            name = str(prov.parent.relative_to(golden / arch))
            d = designs.setdefault(name, Design(name))
            blif = prov.with_name(f"{leaf}.{tool}.blif")
            if read_status(prov) != "ok" or not blif.is_file():
                d.all_ok = False
                continue
            size = blif.stat().st_size
            d.blifs.append(blif.relative_to(golden))
            d.arch_bytes[arch] = d.arch_bytes.get(arch, 0) + size
            d.max_blif = max(d.max_blif, size)
    for d in designs.values():  # a design missing from an arch, or a tool, is not eligible
        if len(d.blifs) != len(archs) * len(TOOLS):
            d.all_ok = False
    return designs


def spread(items: Sequence[Design], k: int) -> list[Design]:
    """k items at evenly spaced ranks of an already-sorted sequence (all of them if <= k)."""
    n = len(items)
    if n <= k:
        return list(items)
    if k == 1:
        return [items[0]]
    ranks = sorted({round(i * (n - 1) / (k - 1)) for i in range(k)})
    return [items[r] for r in ranks]


def eligible(d: Design, max_blif: int) -> bool:
    return d.all_ok and d.max_blif <= max_blif


def select(designs: dict[str, Design], per_group: int, max_blif: int) -> dict[str, list[Design]]:
    groups: dict[str, list[Design]] = defaultdict(list)
    for d in designs.values():
        if eligible(d, max_blif):
            groups[group_of(d.name)].append(d)
    chosen = {g: spread(sorted(ds, key=lambda d: (d.size, d.name)), per_group)
              for g, ds in sorted(groups.items())}
    for name in ALWAYS:
        extra = designs.get(name)
        if extra is not None and extra.all_ok and extra not in chosen.get(group_of(name), []):
            chosen.setdefault(group_of(name), []).append(extra)
    return chosen


def gitignore_block(chosen: dict[str, list[Design]]) -> list[str]:
    paths = sorted(str(p) for ds in chosen.values() for d in ds for p in d.blifs)
    return [BEGIN, "*.blif", *(f"!/{p}" for p in paths), END]


def write_gitignore(path: Path, block: list[str]) -> None:
    lines = path.read_text().splitlines() if path.exists() else []
    if BEGIN in lines:
        if END not in lines[lines.index(BEGIN):]:
            raise SampleError(f"{path}: '{BEGIN}' without '{END}'")
        start = lines.index(BEGIN)
        end = lines.index(END, start)
        lines[start : end + 1] = block
    else:
        lines += ([""] if lines else []) + block
    path.write_text("\n".join(lines) + "\n")


def summarize(designs: dict[str, Design], chosen: dict[str, list[Design]], golden: Path,
              max_blif: int) -> None:
    total = 0
    print(f"{'group':40} {'designs':>7} {'eligible':>8} {'sampled':>7} {'MB':>8}")
    n_eligible: dict[str, int] = defaultdict(int)
    count: dict[str, int] = defaultdict(int)
    for d in designs.values():
        count[group_of(d.name)] += 1
        n_eligible[group_of(d.name)] += eligible(d, max_blif)
    for g in sorted(count):
        ds = chosen.get(g, [])
        size = sum((golden / p).stat().st_size for d in ds for p in d.blifs)
        total += size
        print(f"{g:40} {count[g]:7} {n_eligible[g]:8} {len(ds):7} {size / 1e6:8.2f}")
    n = sum(len(ds) for ds in chosen.values())
    print(f"{'total':40} {len(designs):7} {sum(n_eligible.values()):8} {n:7} {total / 1e6:8.2f}")


def main(argv: Sequence[str]) -> int:
    ap = argparse.ArgumentParser(prog="golden-sample", description=__doc__.split("\n\n")[0])
    ap.add_argument("--golden", type=Path,
                    default=Path(__file__).resolve().parents[2].parent / "golden")
    ap.add_argument("--per-group", type=int, default=5)
    ap.add_argument("--max-blif-mb", type=float, default=2.0)
    ap.add_argument("--write", action="store_true", help="regenerate <golden>/.gitignore block")
    args = ap.parse_args(argv)
    if args.per_group < 1:
        ap.error("--per-group must be >= 1")
    try:
        designs = scan(args.golden)
        max_blif = int(args.max_blif_mb * 1e6)
        chosen = select(designs, args.per_group, max_blif)
        summarize(designs, chosen, args.golden, max_blif)
        if args.write:
            write_gitignore(args.golden / ".gitignore", gitignore_block(chosen))
    except (SampleError, OSError, UnicodeDecodeError) as exc:
        print(f"golden-sample: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
